# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?
MedicalCenter.create([
  { country: "Bangladesh", city: "Dhaka", center_name: "Al-Madina Medical Services", traveling_country: "Saudi Arabia", price: 9000.00 },
  { country: "Bangladesh", city: "Barishal", center_name: "Alif Check-up Services", traveling_country: "Saudi Arabia", price: 9000.00 },
  { country: "Bangladesh", city: "Barishal", center_name: "Barishal Central Diagnostic Center", traveling_country: "Saudi Arabia", price: 4500.00 },
  { country: "Bangladesh", city: "Barishal", center_name: "Yaqeen Medical Centre", traveling_country: "Saudi Arabia", price: 4500.00 },
  { country: "Bangladesh", city: "Barishal", center_name: "Yaqeen Medical Centre", traveling_country: "Kuwait", price: 4500.00 },
  { country: "Bangladesh", city: "Barishal", center_name: "Barishal Central Diagnostic Center", traveling_country: "Kuwait", price: 4500.00},
  { country: "Bangladesh", city: "Barishal", center_name: "Alif Check-up Services", traveling_country: "Kuwait", price: 4500.00 },
  { center_name: "AKS Khan Diagnostics Ltd", country: "Bangladesh", city: "Chittagong", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "Ali Shah Diagnostic & Specialist Doctors Consultation Centre", country: "Bangladesh", city: "Chittagong", traveling_country: "Saudi Arabia", price: 3600.00 },
  { center_name: "Apex Diagnostic Services (pvt) Ltd.", country: "Bangladesh", city: "Chittagong", traveling_country: "Saudi Arabia", price: 3000.00 },
  { center_name: "Check Up Diagnostic Centre", country: "Bangladesh", city: "Chittagong", traveling_country: "Saudi Arabia", price: 3700.00 },
  { center_name: "Green Crescent Medical Diagnostic", country: "Bangladesh", city: "Chittagong", traveling_country: "Saudi Arabia", price: 3500.00 },
  { center_name: "Human Diagnostic and Medical Check-up Center", country: "Bangladesh", city: "Chittagong", traveling_country: "Saudi Arabia", price: 7000.00 },
  { center_name: "Medical Point Diagnostic Center", country: "Bangladesh", city: "Chittagong", traveling_country: "Saudi Arabia", price: 3500.00 },
  { center_name: "Medicare Medical Check-up Centre", country: "Bangladesh", city: "Chittagong", traveling_country: "Saudi Arabia", price: 7000.00 },
  { center_name: "Sunway Medical Centre", country: "Bangladesh", city: "Chittagong", traveling_country: "Saudi Arabia", price: 5500.00 },
  { center_name: "The Urbane Clinical Services", country: "Bangladesh", city: "Chittagong", traveling_country: "Saudi Arabia", price: 3500.00 },
  { center_name: "Turkey Medical Services", country: "Bangladesh", city: "Chittagong", traveling_country: "Saudi Arabia", price: 6000.00 },
  { center_name: "AL MAN MEDICAL CENTER", country: "Bangladesh", city: "Cox's Bazar", traveling_country: "Kuwait", price: 6000.00 },
  { center_name: "Bay Medical Centre", country: "Bangladesh", city: "Cox's Bazar", traveling_country: "Kuwait", price: 6000.00 },
  { center_name: "Chemon Health Care", country: "Bangladesh", city: "Cox's Bazar", traveling_country: "Kuwait", price: 6000.00 },
  { center_name: "MAX MEDICAL CENTER", country: "Bangladesh", city: "Cox's Bazar", traveling_country: "Kuwait", price: 6000.00 },
  { center_name: "Shouq Medical Point", country: "Bangladesh", city: "Cox's Bazar", traveling_country: "Kuwait", price: 6000.00 },
  { center_name: "MAX MEDICAL CENTER", country: "Bangladesh", city: "Cox's Bazar", traveling_country: "Saudi Arabia", price: 7000.00 },
  { center_name: "Chemon Health Care", country: "Bangladesh", city: "Cox's Bazar", traveling_country: "Saudi Arabia", price: 6000.00 },
  { center_name: "Bay Medical Centre", country: "Bangladesh", city: "Cox's Bazar", traveling_country: "Saudi Arabia", price: 7000.00 },
  { center_name: "AL MAN MEDICAL CENTER", country: "Bangladesh", city: "Cox's Bazar", traveling_country: "Saudi Arabia", price: 6000.00 },
  { center_name: "Shouq Medical Point", country: "Bangladesh", city: "Cox's Bazar", traveling_country: "Saudi Arabia", price: 6000.00 },
  { center_name: "Jeeshan Check-up Services", country: "Bangladesh", city: "Cumilla", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "Medi Check Medical Service Limited", country: "Bangladesh", city: "Cumilla", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "Medi Health Medical Center", country: "Bangladesh", city: "Cumilla", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "Reda Hamzah Diagnostic", country: "Bangladesh", city: "Cumilla", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "Tabuk Medical Center", country: "Bangladesh", city: "Cumilla", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "TRUST MEDICAL & DIAGNOSTIC CENTER", country: "Bangladesh", city: "Cumilla", traveling_country: "Saudi Arabia", price: 7000.00 },
  { center_name: "Al-Madina Medical Services", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Green Crescent Health Services", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Saimon Medical Centre", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Gulshan Medicare - Dhaka", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Saudi Bangladesh Services Company", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Arabian Medical Center", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Ibn Sina Medical Check Up Unit", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Al-Humyra Health Centre Ltd", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Al-Riyadh Medical Check up", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Chandshi Medical Center", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Fairways Medical Center", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Gulf Medical Center", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Health Care Center", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Muscat Medical Center", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Makkha Medical Center", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "National Medical Center Limited", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Pulse Medical Center", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Pushpo Clinic", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "International Health Center", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Al Hayatt Medical Centre", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Al-Nahda Medical Centre", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "The Classic Medical Centre Ltd", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Allied Diagnostics Ltd", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Paradyne Medical Centre", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Ibn Rushd Medical Center", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Unique Medical Centre", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Standard Medical Centre", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Leading Health Check up", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "SKN Health Services", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Transworld Medical Center", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Al Mubasher Medical Diagnostic Services", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Orbitals Medical Centre Limited", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Bashundhara Medical Center", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Crystal Diagnostic", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Tulip Medical Center", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "LAB QUEST LIMITED", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "NAFA MEDICAL CENTRE", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Confidence Medical Centre", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "STAR MEDICAL AND DIAGNOSTIC CENTER", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "ADVANCE HEALTH CARE", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Kent Medical Services Ltd.", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Malancha Medical Services Ltd.", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Al Mashoor Diagnostic Services", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "Perlov Medical Services Ltd.", country: "Bangladesh", city: "Dhaka", traveling_country: "Saudi Arabia", price: 9000.00 },
  { center_name: "AL ALI DIAGNOSTIC CENTER", country: "Bangladesh", city: "Rajshahi", traveling_country: "Kuwait", price: 7000.00 },
  { center_name: "AL- NAHIYAN DIAGNOSTIC & MEDICAL SERVICES", country: "Bangladesh", city: "Rajshahi", traveling_country: "Kuwait", price: 7000.00 },
  { center_name: "Hope Medical Centre", country: "Bangladesh", city: "Rajshahi", traveling_country: "Kuwait", price: 7000.00 },
  { center_name: "Labaid Limited (Diagnostics)", country: "Bangladesh", city: "Rajshahi", traveling_country: "Kuwait", price: 7000.00 },
  { center_name: "Nazowa Medical Centre", country: "Bangladesh", city: "Rajshahi", traveling_country: "Kuwait", price: 7500.00 },
  { center_name: "SATATA MEDICAL CHECKUP CENTER", country: "Bangladesh", city: "Rajshahi", traveling_country: "Kuwait", price: 7000.00 },
  { center_name: "AL- NAHIYAN DIAGNOSTIC & MEDICAL SERVICES", country: "Bangladesh", city: "Rajshahi", traveling_country: "Saudi Arabia", price: 7000.00 },
  { center_name: "Hope Medical Centre", country: "Bangladesh", city: "Rajshahi", traveling_country: "Saudi Arabia", price: 7000.00 },
  { center_name: "Nazowa Medical Centre", country: "Bangladesh", city: "Rajshahi", traveling_country: "Saudi Arabia", price: 7000.00 },
  { center_name: "SATATA MEDICAL CHECKUP CENTER", country: "Bangladesh", city: "Rajshahi", traveling_country: "Saudi Arabia", price: 7000.00 },
  { center_name: "AL ALI DIAGNOSTIC CENTER", country: "Bangladesh", city: "Rajshahi", traveling_country: "Saudi Arabia", price: 7000.00 },
  { center_name: "Labaid Limited (Diagnostics)", country: "Bangladesh", city: "Rajshahi", traveling_country: "Saudi Arabia", price: 7000.00 },  
  { center_name: "A. Rahman Medical Center", country: "Bangladesh", city: "Sylhet", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "ABC Diagnostic Center", country: "Bangladesh", city: "Sylhet", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "Al-Hamad Medical Centre Ltd", country: "Bangladesh", city: "Sylhet", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "Al-Khaled Medical Services", country: "Bangladesh", city: "Sylhet", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "Green Crescent Medilab", country: "Bangladesh", city: "Sylhet", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "J B Medical Center Ltd", country: "Bangladesh", city: "Sylhet", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "Medinova Medical Services", country: "Bangladesh", city: "Sylhet", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "Sylhet City Medical Centre", country: "Bangladesh", city: "Sylhet", traveling_country: "Saudi Arabia", price: 5000.00 },
  { center_name: "Sylhet City Medical Centre", country: "Bangladesh", city: "Sylhet", traveling_country: "Kuwait", price: 5000.00 },
  { center_name: "Medinova Medical Services", country: "Bangladesh", city: "Sylhet", traveling_country: "Kuwait", price: 5000.00 },
  { center_name: "J B Medical Center Ltd", country: "Bangladesh", city: "Sylhet", traveling_country: "Kuwait", price: 5000.00 },
  { center_name: "Green Crescent Medilab", country: "Bangladesh", city: "Sylhet", traveling_country: "Kuwait", price: 5000.00 },
  { center_name: "Al-Khaled Medical Services", country: "Bangladesh", city: "Sylhet", traveling_country: "Kuwait", price: 5000.00 },
  { center_name: "Al-Hamad Medical Centre Ltd", country: "Bangladesh", city: "Sylhet", traveling_country: "Kuwait", price: 5000.00 },
  { center_name: "ABC Diagnostic Center", country: "Bangladesh", city: "Sylhet", traveling_country: "Kuwait", price: 5000.00 },
  { center_name: "A. Rahman Medical Center", country: "Bangladesh", city: "Sylhet", traveling_country: "Kuwait", price: 5000.00 }
])